version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=verySecrert_passXD
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: ./lms_backend  # Build the Dockerfile inside the lms_backend folder
    container_name: lms_backend
    depends_on:
      - db
    env_file:
      - ./lms_backend/docker.env
    ports:
      - "5000:5000"  # Expose port 5000 from the container to the host
    volumes:
      - ./lms_backend:/usr/src/app  # Mount the local lms_backend directory to the container
      - /usr/src/app/node_modules  # Bind mount node_modules directory to avoid potential issues
    command: npm run start:dev  # Run the app in development mode

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db